{% set name = "pyebsdindex" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyebsdindex-{{ version }}.tar.gz
  sha256: 2c8456b45bf2bf8d152650fc063927d9ebb62a0cbb24836c890e9658b16907ee

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38]
  # Skip macOS until ray-default is available for macOS or the package becomes
  # an optional dependency of PyEBSDIndex
  skip: true  # [osx]

requirements:
  host:
    - pip
    - python
  run:
    - h5py
    - jupyterlab
    - matplotlib-base
    - numba
    - numpy
    - ocl-icd-system  # [unix]
    - pyopencl
    - pyswarms
    - python
    - ray-default
    - scipy

test:
  requires:
    - pytest
  imports:
    - pyebsdindex
    - pyebsdindex.ebsd_index
    - pyebsdindex.nlpar
    - pyebsdindex.pcopt
  commands:
    - pytest --pyargs pyebsdindex

about:
  home: https://pyebsdindex.readthedocs.io
  license_file: License
  license: LicenseRef-PyEBSDIndex
  summary: Python based tool for Hough/Radon based EBSD indexing
  doc_url: https://pyebsdindex.readthedocs.io
  dev_url: https://github.com/USNavalResearchLaboratory/PyEBSDIndex

extra:
  recipe-maintainers:
    - drowenhorst-nrl
    - hakonanes
